### ISSUE TITLE
[FEATURE REQUEST]View broken (ugly) with touch ui

### ISSUE THREAD

**Issue by devildant** [cp2004/OctoPrint-EEPROM-Marlin#20]
#### Describe the request
Hello, 
small problem with the touchui plugin and your plugin
![image](https://user-images.githubusercontent.com/8700106/103042794-0610f280-457b-11eb-9e22-d9ed8367f887.png)

`octoprint.log`:

#### Versions, system information

**Plugin** Version: 3.0.0

**OctoPrint**

Version: 1.5.2

Operating System running OctoPrint: octopi 0.17.0

**Printer** model & firmware version: CR-10S marlin 1.1.9

**Browser:** chrome safari (ios)...

**Additional context, screenshots, anything else you think might be useful**

**Comment by devildant** [comment]
feature reuest too :)

**Comment by cp2004** [comment]
Interestingly, the table clipping off the side is actually a touchUI problem (IMO) since it applies the `width: 100mv` (meaning 100%). 

Overriding this, to set `width: auto; min-width: 100%` on the style improves this significantly:
![image](https://user-images.githubusercontent.com/31997505/103103111-4aea6700-4617-11eb-85bb-f6e030eaced0.png)

For the icons, that is also touchUI being a little annoying in applying it's custom font to *everything*, which wipes out my custom FA5 icon set. I might be able to override this too, but it is not going to be clean lol:
![image](https://user-images.githubusercontent.com/31997505/103103256-cc41f980-4617-11eb-9cd6-0be52dce2b47.png)

A little extra margin can be applied to buttons to make them look a little nicer, maybe just the backup button.


Maybe you didn't want to know all that, but that was from my experimenting the browser console so I needed to keep track of it!

**Comment by cp2004** [comment]
Similarly to #19, brought forward as it is a minor change that *might as well* go out with the bugfix release later today. It's the best I can do, to make it somewhat coordinated without re-writing the whole interface if touch UI is enabled.
