### ISSUE TITLE
[Request]  Another data point to check : MeatPack

### ISSUE THREAD

**Issue by KenLucke** [cp2004/OctoPrint-EEPROM-Marlin#28]
This looks as if it will get supported in a variety of firmware branches (I know that the guy doing my firmware, and that for several Creality models is already testing it).  Can you add a check for it?

https://plugins.octoprint.org/plugins/meatpack/

**Comment by cp2004** [comment]
I would imagine it would be reported in the capability report (M115), in which case it should just show up if there is a branch of firmware that has this implemented - previous ones don't say 'i don't support it' because they don't know it exists.

If it doesn't show up in the capability report... Well then that's more difficult.

**Comment by cp2004** [comment]
@KenLucke Can you confirm that on firmware with the MeatPack feature existing this shows up in the cap report?

**Comment by KenLucke** [comment]
Yes, it does.

<img width="821" alt="image" src="https://user-images.githubusercontent.com/57936294/108842149-b1dfba00-758d-11eb-93ab-1495a2cfe64c.png">

**Comment by KenLucke** [comment]
As I opened this, and it was [automatically] resolved, I might as well close it.

**Comment by cp2004** [comment]
Thanks for confirming 🙂
