### ISSUE TITLE
[Request]: Using eprom locked on iPad

### ISSUE THREAD

**Issue by Mardak62** [cp2004/OctoPrint-EEPROM-Marlin#73]
### What do you need help with?

when connecting to octoprint web interface 

and trying to use eprom on an Ipad, I get the message:

Read Only

looks like the printer is locked

see attached screen capture

But no such issue when connecting from My Mac.

![IMG_0003](https://user-images.githubusercontent.com/35977246/229637157-f74bdc7b-230a-42e4-b408-6f87c053a502.PNG)

**Comment by cp2004** [comment]
What version of iOS is your iPad running?

**Comment by Mardak62** [comment]
I am using an old iPad with iOS 9.3.5 to follow the print when I am running around the building.

Thank you
brads
Amir

**Comment by cp2004** [comment]
iOS 9.3.5 is too old to run this plugin in the browser unfortunately, since it uses some modern JavaScript features that are not available there.

Please also go to https://octoprint.org/browser-check - OctoPrint 1.9.0 modernises some of the JavaScript there too, and so if any of the tests there show 'no' you won't be able to use this iPad to access OctoPrint 1.9.0 in the future at all, it won't just be this plugin that is broken. This decision was made on the basis of only 0.15% of users (who opted into anonymous usage tracking) still running old browsers to connect to OctoPrint, we didn't want to hold back development any more.

**Comment by Mardak62** [comment]
Understood, thank you very much. One last question, I need to fix my hotend xyz POS offset (installed a new swiss direct drive); Is that a possibility for the future versions do that  in eprom reader? or maybe it is possible and I am missing something. Thank you best regards

**Comment by cp2004** [comment]
Sounds like you might need the 'Home offsets' part (M206), which will show up if your printer allows these to be configured.

**Comment by cp2004** [comment]
I'm going to close this issue as the root problem is something I won't fix. Feel free to still add comments if necessary.
